<a href="https://colab.research.google.com/github/ankit-144/Age-recognition/blob/main/main_Age_Detection_of_Indian_Actors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -U scipy==1.2.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import os
import random
import numpy as np
import keras
from keras.models import Sequential
from keras.layers.core import Flatten, Dense, Dropout
from keras.layers.convolutional import Convolution2D, MaxPooling2D, ZeroPadding2D
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from scipy.misc import imread
from scipy.misc import imresize
from tensorflow.keras.optimizers import SGD, Adam, Adamax


root_dir = os.path.abspath('.')
data_dir = ''

In [ ]:
from zipfile import ZipFile
file_name = '/content/drive/MyDrive/Colab Notebooks/ Age-Detection-of-Indian-Actors/train_DETg9GD.zip'

with ZipFile(file_name, 'r') as zip:
 zip.extractall()
print('Done')

Done


In [ ]:
from zipfile import ZipFile
file_name = '/content/drive/MyDrive/Colab Notebooks/ Age-Detection-of-Indian-Actors/test_Bh8pGW3.zip'

with ZipFile(file_name, 'r') as zip:
 zip.extractall()
print('Done')

Done


In [ ]:
train = pd.read_csv(os.path.join(data_dir, '/content/train.csv'))
test = pd.read_csv(os.path.join(data_dir, '/content/drive/MyDrive/Colab Notebooks/ Age-Detection-of-Indian-Actors/test_Bh8pGW3/test.csv'))

In [ ]:
train.ID[:2000]

0         377.jpg
1       17814.jpg
2       21283.jpg
3       16496.jpg
4        4487.jpg
          ...    
1995    14775.jpg
1996    16928.jpg
1997    24886.jpg
1998    18537.jpg
1999      183.jpg
Name: ID, Length: 2000, dtype: object

In [ ]:
test

ID
0     25321.jpg
1       989.jpg
2     19277.jpg
3     13093.jpg
4      5367.jpg
...         ...
6631   1876.jpg
6632  14940.jpg
6633   3638.jpg
6634    376.jpg
6635   9357.jpg

[6636 rows x 1 columns]

In [ ]:
#root_dir = os.path.abspath('.')
#data_dir = ''
temp = []
for img_name in train.ID:
    img_path = os.path.join(data_dir, '/content/Train', img_name)
    img = imread(img_path)
    img = imresize(img, (64, 64))
    img = img.astype('float32') # this will help us in later stage
    temp.append(img)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning:     `imread` is deprecated!
    `imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
    Use ``imageio.imread`` instead.
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning:     `imresize` is deprecated!
    `imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.3.0.
    Use Pillow instead: ``numpy.array(Image.fromarray(arr).resize())``.
  import sys


In [ ]:
img_path

'/content/Train/9896.jpg'

In [ ]:
train_x = np.stack(temp)

In [ ]:
root_dir = os.path.abspath('.')
data_dir = ''
temp = []
for img_name in test.ID:
    img_path = os.path.join(data_dir, '/content/Test', img_name)
    img = imread(img_path)
    img = imresize(img, (64,64))
    img = img.astype('float32') # this will help us in later stage
    temp.append(img)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning:     `imread` is deprecated!
    `imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
    Use ``imageio.imread`` instead.
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning:     `imresize` is deprecated!
    `imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.3.0.
    Use Pillow instead: ``numpy.array(Image.fromarray(arr).resize())``.
  import sys


In [ ]:
test_x = np.stack(temp)

In [ ]:
lb = LabelEncoder()
train_y = lb.fit_transform(train.Class)

In [ ]:
train_y[:30]

array([0, 2, 0, 2, 0, 0, 2, 2, 2, 1, 2, 0, 0, 0, 0, 0, 1, 2, 1, 0, 2, 1,
       2, 0, 0, 2, 0, 1, 0, 2])

In [ ]:
train_x.shape

(19906, 64, 64, 3)

In [ ]:
train_y.shape

(19906,)

In [ ]:
train_y[:30]

array([0, 2, 0, 2, 0, 0, 2, 2, 2, 1, 2, 0, 0, 0, 0, 0, 1, 2, 1, 0, 2, 1,
       2, 0, 0, 2, 0, 1, 0, 2])

In [ ]:
test_x /= 255
train_x /= 255

In [ ]:
from sklearn.model_selection import train_test_split
x1_train, x1_test, y1_train, y1_test = train_test_split(train_x, train_y, test_size=0.25, random_state=42, stratify=np.array(train_y))

In [ ]:
x1_train[0]

array([[[0.16078432, 0.11764706, 0.14901961],
        [0.15686275, 0.11372549, 0.14509805],
        [0.15294118, 0.10980392, 0.14117648],
        ...,
        [0.1764706 , 0.10980392, 0.07058824],
        [0.23137255, 0.18039216, 0.12156863],
        [0.26666668, 0.22352941, 0.15294118]],

       [[0.15686275, 0.11372549, 0.14509805],
        [0.15294118, 0.10980392, 0.14117648],
        [0.14901961, 0.10588235, 0.13725491],
        ...,
        [0.16078432, 0.09411765, 0.05490196],
        [0.2       , 0.14901961, 0.09019608],
        [0.22745098, 0.18039216, 0.11372549]],

       [[0.16078432, 0.11372549, 0.14901961],
        [0.15686275, 0.10980392, 0.14509805],
        [0.15686275, 0.10980392, 0.14117648],
        ...,
        [0.14901961, 0.08235294, 0.04705882],
        [0.16862746, 0.11372549, 0.06666667],
        [0.18039216, 0.13333334, 0.07843138]],

       ...,

       [[0.3764706 , 0.19215687, 0.15294118],
        [0.4117647 , 0.22745098, 0.1882353 ],
        [0.46666667, 0

In [ ]:
from tensorflow.keras import datasets, layers, models

In [ ]:
ann = models.Sequential([
        layers.Flatten(input_shape=(64,64,3)),
        layers.Dense(3000, activation='relu'),
        layers.Dense(2000, activation='relu'),
        layers.Dense(1000, activation='relu'),
        layers.Dense(500, activation='relu'),
        layers.Dense(10, activation='softmax')    
    ])

ann.compile(optimizer='SGD',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

ann.fit(x1_train, y1_train, epochs=10)

Epoch 1/10
467/467 [==============================] - 4s 7ms/step - loss: 0.9254 - accuracy: 0.5627
Epoch 2/10
467/467 [==============================] - 3s 7ms/step - loss: 0.8375 - accuracy: 0.6110
Epoch 3/10
467/467 [==============================] - 3s 7ms/step - loss: 0.8063 - accuracy: 0.6339
Epoch 4/10
467/467 [==============================] - 3s 7ms/step - loss: 0.7827 - accuracy: 0.6459
Epoch 5/10
467/467 [==============================] - 3s 7ms/step - loss: 0.7647 - accuracy: 0.6538
Epoch 6/10
467/467 [==============================] - 3s 7ms/step - loss: 0.7448 - accuracy: 0.6663
Epoch 7/10
467/467 [==============================] - 3s 7ms/step - loss: 0.7308 - accuracy: 0.6723
Epoch 8/10
467/467 [==============================] - 4s 9ms/step - loss: 0.7158 - accuracy: 0.6842
Epoch 9/10
467/467 [==============================] - 3s 7ms/step - loss: 0.7015 - accuracy: 0.6883
Epoch 10/10
467/467 [==============================] - 3s 7ms/step - loss: 0.6911 - accuracy: 0.6976

In [ ]:
ann.evaluate(x1_test,y1_test)

156/156 [==============================] - 1s 4ms/step - loss: 0.8954 - accuracy: 0.5971


[0.8954330682754517, 0.5971468687057495]

In [ ]:
data_augmentation = keras.Sequential(
  [
    layers.experimental.preprocessing.RandomFlip("horizontal", 
                                                 input_shape=(64, 64, 3)),
    layers.experimental.preprocessing.RandomRotation(0.1),
    layers.experimental.preprocessing.RandomZoom(0.1),
  ]
)

In [ ]:
cnn = models.Sequential([
      data_augmentation,                    
    layers.Conv2D(filters=32, kernel_size=(3, 3), padding='same', activation='relu', input_shape=(64, 64, 3)),
    layers.MaxPooling2D((2, 2)),
  
    layers.Conv2D(filters=64, kernel_size=(3, 3), padding='same', activation='relu'),
    layers.MaxPooling2D((2, 2)),

     layers.Conv2D(filters=128, kernel_size=(3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
   
    layers.Dropout(0.2),
   
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(100, activation='softmax')
])

In [ ]:
cnn.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
cnn.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 sequential_3 (Sequential)   (None, 64, 64, 3)         0         
                                                                 
 conv2d_3 (Conv2D)           (None, 64, 64, 32)        896       
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 32, 32, 32)       0         
 2D)                                                             
                                                                 
 conv2d_4 (Conv2D)           (None, 32, 32, 64)        18496     
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 16, 16, 64)       0         
 2D)                                                             
                                                                 
 conv2d_5 (Conv2D)           (None, 14, 14, 128)      

In [ ]:
cnn.fit(x1_train, y1_train, epochs=30)

Epoch 1/30
467/467 [==============================] - 4s 10ms/step - loss: 0.6205 - accuracy: 0.7361
Epoch 2/30
467/467 [==============================] - 4s 8ms/step - loss: 0.6105 - accuracy: 0.7412
Epoch 3/30
467/467 [==============================] - 4s 9ms/step - loss: 0.6006 - accuracy: 0.7439
Epoch 4/30
467/467 [==============================] - 4s 8ms/step - loss: 0.5860 - accuracy: 0.7488
Epoch 5/30
467/467 [==============================] - 4s 8ms/step - loss: 0.5713 - accuracy: 0.7599
Epoch 6/30
467/467 [==============================] - 4s 8ms/step - loss: 0.5637 - accuracy: 0.7604
Epoch 7/30
467/467 [==============================] - 4s 8ms/step - loss: 0.5554 - accuracy: 0.7665
Epoch 8/30
467/467 [==============================] - 4s 9ms/step - loss: 0.5517 - accuracy: 0.7660
Epoch 9/30
467/467 [==============================] - 4s 8ms/step - loss: 0.5349 - accuracy: 0.7759
Epoch 10/30
467/467 [==============================] - 4s 8ms/step - loss: 0.5249 - accuracy: 0.781

In [ ]:
cnn.evaluate(x1_test,y1_test)

156/156 [==============================] - 1s 5ms/step - loss: 0.4720 - accuracy: 0.8194


[0.47202324867248535, 0.8193690776824951]

In [ ]:
y_pred = cnn.predict(test_x)
y_pred[:1]

array([[9.63211477e-01, 1.70231964e-02, 1.97652616e-02, 6.39288023e-20,
        4.61420423e-19, 1.33596778e-20, 1.44756581e-19, 8.45186318e-19,
        1.06292295e-19, 8.02571666e-21, 2.46338833e-19, 9.16762308e-19,
        4.40690398e-19, 5.95511828e-19, 6.62885482e-20, 2.10084246e-20,
        4.43033335e-19, 1.01564977e-19, 4.28068009e-19, 1.28927084e-19,
        4.31868122e-20, 6.80007656e-19, 6.62868163e-19, 3.15666442e-19,
        1.81889869e-19, 2.32277124e-19, 5.07225407e-20, 4.42209308e-19,
        2.52308440e-20, 2.42155470e-19, 8.29689426e-20, 1.85923616e-19,
        3.59005013e-20, 3.71049110e-18, 1.27549120e-18, 1.60404628e-19,
        3.46110385e-19, 3.33291813e-20, 2.87346163e-20, 2.59740544e-18,
        2.00822870e-19, 5.21230576e-20, 5.05622001e-20, 5.84976572e-20,
        3.80978581e-19, 1.20908060e-19, 4.69223424e-19, 2.27393786e-19,
        1.64498164e-19, 2.13134820e-19, 1.34792751e-18, 1.88085077e-19,
        5.29026850e-20, 9.18309446e-19, 2.57493198e-18, 1.133302

In [ ]:
y_classes = [np.argmax(element) for element in y_pred]
y_classes[:5]

[0, 2, 2, 0, 1]

In [ ]:
IMG_SHAPE = (64,64, 3)
import tensorflow as tf
VGG16_MODEL=tf.keras.applications.VGG16(input_shape=IMG_SHAPE,
                                               include_top=False,
                                               weights='imagenet')

In [ ]:
data_augmentation = keras.Sequential(
  [
    layers.experimental.preprocessing.RandomFlip("horizontal", 
                                                 input_shape=(64, 64, 3)),
    layers.experimental.preprocessing.RandomRotation(0.1),
    layers.experimental.preprocessing.RandomZoom(0.1),
  ]
)

In [ ]:
VGG16_MODEL.trainable=False
global_average_layer = tf.keras.layers.GlobalAveragePooling2D()
prediction_layer = tf.keras.layers.Dense(3,activation='softmax')

In [ ]:
model = tf.keras.Sequential([
  VGG16_MODEL,
  global_average_layer,
  prediction_layer
])

In [ ]:
model.compile(optimizer=tf.optimizers.Adam(), 
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=["accuracy"])

In [ ]:
history = model.fit(x1_train, y1_train, epochs=20)

Epoch 1/20
467/467 [==============================] - 8s 18ms/step - loss: 0.7230 - accuracy: 0.6839
Epoch 2/20
467/467 [==============================] - 8s 18ms/step - loss: 0.7180 - accuracy: 0.6888
Epoch 3/20
467/467 [==============================] - 9s 18ms/step - loss: 0.7149 - accuracy: 0.6884
Epoch 4/20
467/467 [==============================] - 9s 18ms/step - loss: 0.7141 - accuracy: 0.6901
Epoch 5/20
467/467 [==============================] - 8s 18ms/step - loss: 0.7101 - accuracy: 0.6917
Epoch 6/20
467/467 [==============================] - 8s 18ms/step - loss: 0.7078 - accuracy: 0.6928
Epoch 7/20
467/467 [==============================] - 8s 18ms/step - loss: 0.7061 - accuracy: 0.6925
Epoch 8/20
467/467 [==============================] - 8s 18ms/step - loss: 0.7041 - accuracy: 0.6944
Epoch 9/20
467/467 [==============================] - 8s 18ms/step - loss: 0.7022 - accuracy: 0.6962
Epoch 10/20
467/467 [==============================] - 8s 18ms/step - loss: 0.7006 - accura

**transfer** **learning**

ddf


In [ ]:
aged=["MIDDLE","OLD","YOUNG"]

In [ ]:
print(y_classes)
print(len(y_classes))

In [ ]:
submission= pd.DataFrame({
     "Class": y_classes,
    "ID":test[ "ID"]
   
    
})

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import PIL
import tensorflow as tf
from keras.models import Sequential
from keras.layers.core import Flatten, Dense, Dropout
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

In [ ]:
resnet_model = Sequential()

pretrained_model= tf.keras.applications.ResNet50(include_top=False,
                   input_shape=(64,64,3),
                   pooling='avg',
                   weights='imagenet')
for layer in pretrained_model.layers:
        layer.trainable=False

resnet_model.add(pretrained_model)

In [ ]:
resnet_model.add(Flatten())
resnet_model.add(Dense(64, activation='relu'))
resnet_model.add(Dense(1, activation='softmax'))

In [ ]:
resnet_model.summary()

In [ ]:
resnet_model.compile(optimizer=Adam(lr=0.001),loss='categorical_crossentropy',metrics=['accuracy'])

history = resnet_model.fit(x1_train, y1_train, epochs=10)

In [ ]:
#submission.to_csv("submission Age-Detection-of-Indian-Actors.csv",index=False)

In [ ]:
#submission = pd.read_csv("submission Age-Detection-of-Indian-Actors.csv")

In [ ]:
#submission['Class'].replace(0, "MIDDLE",inplace = True)
#submission['Class'].replace(1, "OLD",inplace = True)
#submission['Class'].replace(2, "YOUNG",inplace = True)

In [ ]:
#pd.DataFrame(submission, columns= ['Class', 'ID']).to_csv('logistic.csv')

In [ ]:
!pip install --upgrade imutils

In [ ]:
from resnet import ResNet

ModuleNotFoundError: ignored